import Carousel from "./Carousel";

interface Props {
  onOpenTest: () => void;
}

/* october 2026: the whole Gallery game at the end of the timeline — the
   nav's gallery link scrolls here. */

export default function GallerySection({ onOpenTest }: Props) {
  return (
    <div className="ngs-gallery" id="gallery">
      <article className="gallery-feature">
        {/* The title is a one-time baked render: the game's ink-outline style
            around the blackletter, generated by tools/bake-title-ink.* — edit
            the copy there and re-run the driver, never draw it live. The ?v=
            on the src busts caches: bump it on every re-bake. */}
        <div className="game-copy">
          <h2 id="games-heading" className="game-title">
            <img src="assets/gallery-title-ink.svg?v=6" alt="Gallery" width={343} height={128} />
          </h2>
          <p className="game-description">a drawing deduction game for the browser. Now in beta</p>
        </div>
        <a className="button play-gallery" href="https://gallery.newgamestudio.com/" target="_blank" rel="noopener noreferrer">Play for free <span aria-hidden="true">↗</span></a>
      </article>

      {/* Development images: the Carousel component. Help us test: opens
          the playtest questionnaire. */}
      <Carousel />

      <div className="help-test">
        <h2 className="fools-title">help us <span>test</span></h2>
        <p className="fools-caption">we need people to play it and fill this thing out:</p>
        <button type="button" className="nav-money" id="open-test" onClick={onOpenTest}>
          questionnaire <span aria-hidden="true">↗</span>
        </button>
      </div>
    </div>
  );
}
